### PR TITLE
fixed some failing edge cases and added some tests

### PR DESCRIPTION
**Pull request by jameslnewell**

### CODE REVIEW

**Comment by danmactough** [comment]
Hi, @jameslnewell Thanks for the PR! We'll need to add a test runner to run these tests. Let's use mocha. I added you as a collaborator to this repo. Do you want to add the test runner and either update this PR or resubmit using a working branch in this repo?

**Comment by jameslnewell** [comment]
Hi @danmactough. Ty. Added a `scripts` key to run the tests.

**Comment by danmactough** [comment]
:+1: Thanks!

**Comment by danmactough** [comment]
Released as v1.0.0 fbb5bea3780ff933e09675d2e077e1b9a0f07e8a

**Comment by jameslnewell** [comment]
Ty.

**Pull request merged**
